

#include "throttle.h"

#define MAX_THROTTLE	(170 * 5)
#define MIN_THROTTLE  (125 * 5)
#define STEP_THROTTLE	(2 * 5)

void increaseThrottle(void){

	if ((TIM2->CCR3 + 1) >= MAX_THROTTLE){
		TIM2->CCR2 = MAX_THROTTLE;
		TIM2->CCR3 = MAX_THROTTLE;
		TIM1->CCR3 = MAX_THROTTLE;
		TIM1->CCR4 = MAX_THROTTLE;
	}else{
	TIM2->CCR2 += STEP_THROTTLE;
	TIM2->CCR3 += STEP_THROTTLE;
	TIM1->CCR3 += STEP_THROTTLE;
	TIM1->CCR4 += STEP_THROTTLE;
	}
}
void decreaseThrottle(void){

	if ((TIM2->CCR3 - 1) <= MIN_THROTTLE){
		TIM2->CCR2 = MIN_THROTTLE;
		TIM2->CCR3 = MIN_THROTTLE;
		TIM1->CCR3 = MIN_THROTTLE;
		TIM1->CCR4 = MIN_THROTTLE;
	}else{
	TIM2->CCR2 -= STEP_THROTTLE;
	TIM2->CCR3 -= STEP_THROTTLE;
	TIM1->CCR3 -= STEP_THROTTLE;
	TIM1->CCR4 -= STEP_THROTTLE;
	}
}

void killThrottle(void){
	TIM2->CCR2 = MIN_THROTTLE;
	TIM2->CCR3 = MIN_THROTTLE;
	TIM1->CCR3 = MIN_THROTTLE;
	TIM1->CCR4 = MIN_THROTTLE;
}
